### ISSUE TITLE
No response from slack claude response

### ISSUE THREAD

**Issue by bssbgax75894** [LlmKira/claude-in-slack-server#2]
I can see the conversation sent to slack and Claude responsed in slack. However the server can not get the response from slack.
Step1:
I sent the message to the server, and the server sent to slack.
![image](https://github.com/LlmKira/claude-in-slack-server/assets/112878809/b6ffab04-9664-4d1a-b4d0-21bc70a29547)
Step2:
Slack get the message and claude responsed the message.
![image](https://github.com/LlmKira/claude-in-slack-server/assets/112878809/4b054acb-0870-423d-8987-125855a2a261)
Step3:
The server can not get the response:
I add a print log here, and I found it blocked and never get the response in label 2.
![image](https://github.com/LlmKira/claude-in-slack-server/assets/112878809/1f1d2e50-6603-44a9-9b01-717da282aef0)

**Comment by bssbgax75894** [comment]
Ok, my bad. I miss the step3 guide: Invite your app and Claude to a channel of the workspace, and take down the channel id from url. 
It works now, thanks!!

**Comment by alon-sys** [comment]
@bssbgax75894 I have invited my app and cloud to the workspace channel, but still the same keeps getting no response from tab 2
